# Generated by Django 5.0.3 on 2024-05-10 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='estimation',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
    ]
