# Generated by Django 5.0.3 on 2024-05-19 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wewe', '0003_workers_alter_services_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='worker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='wewe.workers', verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Имя'),
        ),
    ]
